import React from 'react';
import { XIcon } from './icons/XIcon';

interface TermsModalProps {
    isOpen: boolean;
    onClose: () => void;
}

export const TermsModal: React.FC<TermsModalProps> = ({ isOpen, onClose }) => {
    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4" role="dialog" aria-modal="true" aria-labelledby="terms-title">
            <div className="bg-panel border border-border rounded-xl shadow-2xl max-w-3xl w-full h-full max-h-[80vh] flex flex-col animate-fade-in-up" style={{animationDuration: '0.3s'}}>
                <div className="flex justify-between items-center p-6 border-b border-border flex-shrink-0">
                    <h2 id="terms-title" className="text-xl font-bold text-text-primary">Terms of Service</h2>
                    <button onClick={onClose} className="text-text-secondary hover:text-text-primary" aria-label="Close Terms of Service">
                        <XIcon className="w-6 h-6" />
                    </button>
                </div>
                <div className="p-6 overflow-y-auto text-text-secondary space-y-4 text-sm">
                    <h3 className="text-lg font-semibold text-text-primary">Welcome to StepSolve!</h3>
                    <p>These terms and conditions outline the rules and regulations for the use of StepSolve's Website.</p>
                    
                    <h4 className="font-semibold text-text-primary pt-2">1. Acceptance of Terms</h4>
                    <p>By accessing this website, we assume you accept these terms and conditions. Do not continue to use StepSolve if you do not agree to all of the terms and conditions stated on this page.</p>
                    
                    <h4 className="font-semibold text-text-primary pt-2">2. User Responsibilities</h4>
                    <p>You are responsible for your own use of the services, including the provision of a valid API key for accessing Google's AI services. You agree not to use the service for any illegal activities or to violate any laws in your jurisdiction.</p>

                    <h4 className="font-semibold text-text-primary pt-2">3. Disclaimer of Warranties</h4>
                    <p>The service is provided "as is". StepSolve and its suppliers and licensors hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. The explanations and solutions are generated by an AI and may contain errors or inaccuracies. You should verify the results before relying on them for critical applications.</p>
                    
                    <h4 className="font-semibold text-text-primary pt-2">4. Limitation of Liability</h4>
                    <p>In no event will StepSolve, or its suppliers or licensors, be liable with respect to any subject matter of this agreement under any contract, negligence, strict liability or other legal or equitable theory for: (i) any special, incidental or consequential damages; (ii) the cost of procurement for substitute products or services; or (iii) for interruption of use or loss or corruption of data.</p>
                    
                    <h4 className="font-semibold text-text-primary pt-2">5. Changes</h4>
                    <p>StepSolve reserves the right, at its sole discretion, to modify or replace any part of this Agreement. It is your responsibility to check this Agreement periodically for changes.</p>

                </div>
                 <div className="p-6 border-t border-border flex-shrink-0 text-right">
                    <button onClick={onClose} className="px-6 py-2 bg-primary hover:opacity-90 text-white font-bold rounded-lg transition-colors duration-200">
                        Close
                    </button>
                </div>
            </div>
        </div>
    );
};
